services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10010:10000"
      - "10011:10001"
      - "10012:10002"
    networks:
      - azurefunctions

  functionapp:
    image: nebula-dev:1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./docker.env
    volumes:
      - .:/home/site/wwwroot
    environment:
      - AZURE_FUNCTIONS_ENVIRONMENT=Development
      - FUNCTIONS_WORKER_RUNTIME_LOG_LEVEL=Debug  # Specify the path to your environment file
    ports:
      - "7071:80"
    networks:
      - azurefunctions
    depends_on:
      - azurite

networks:
  azurefunctions:
    driver: bridge